### ISSUE TITLE
Pale Moon 28 compatibility

### ISSUE THREAD

**Issue by mineperse** [meganz/firefox-extension#6]
PM 28 labels the plugin as incompatible and disables it.
Kindly requesting this to be fixed.

**Comment by gitbugged** [comment]
Minimal changes required:

* Need a Pre-WebExt version, or need more fix stuff.
* Update GUID to match PM28
* WebStorageAPI doesn't exist and has only recently existed (FF57+) so not sure what to do there, probably remove the storage check in `firefox-extension.jsm`.
* Functions are not scoped properly causing errors.

My attempt at getting this addon working:

In install.rdf:
```
		<em:targetApplication> 
			<Description>
				<!-- PaleMoon -->
				<em:id>{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}</em:id>
				<em:minVersion>27.0</em:minVersion>
				<em:maxVersion>28.*</em:maxVersion>
			</Description>
		</em:targetApplication>
```

Then add the following to meths/firefox-extension.js:
`var EXPORTED_SYMBOLS = ["FirefoxIO", "MemoryIO", "mozIOSetup"];`

Then rename `meths/firefox-extension.js` to `meths/firefox-extension.jsm` and call it in `mega/js/transfers/meths.js`:
```
        Components.utils.import("chrome://mega/content/js/transfers/meths/firefox-extension.jsm");
	dlMethod = FirefoxIO;
```

After doing this, it installs and runs, but fails on Soon() during download and I have no idea what or where the Soon is supposed to come from. It is out of scope which is why it fails. Seems related to timers or crypto, but not much internal documentation beyond this point.

@cr-nz and @diegocr This should probably be removed from the extensions page until this is resolved. It is very confusing to users. It would be nice to have support for this addon however.

**Comment by diegocr** [comment]
Thanks guys for bringing that to our attention, and @gitbugged for the hints.

Do you guys know if there is some official statement from the PaleMoon Team about compatibility breaking changes etc, something like the [Changes for web developers](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/65) that Mozila does publish periodically?

A quick Google search did lead me to https://forum.palemoon.org/viewtopic.php?t=19727 which basically seem to state that PaleMoon will refuse to use Firefox extensions unless they does target PaleMoon specifically (I.e. the `install.rdf` changes you did pointed @gitbugged)

However, I have freshly installed PaleMoon **28.2.1** and gave it a quick try, first installing some of my personal legacy Firefox extensions, and then a in-development MEGA extension (loaded through a so called [extension proxy file](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Setting_up_extension_development_environment#Firefox_extension_proxy_file)) and all these extensions did install fine despite they does not target PaleMoon on their `install.rdf` file, although they does seem to work under some "compatibility" mode...

![184830202248](https://user-images.githubusercontent.com/734313/49313660-dbf5bf00-f4df-11e8-9ea0-d7fc785c0e01.png)

I'm of course getting the same than you guys by attempting to install the official MEGA extension that we're providing from our site, PaleMoon refuses it...

![184830204639](https://user-images.githubusercontent.com/734313/49314049-1e6bcb80-f4e1-11e8-9b3a-5ae1277f7e08.png)

From this i can only think that they may be blacklisting _certain_ extensions from being installed unless they do target PaleMoon - would be nice to know what criteria is behind that...

Whatever, moving forward on the issue(s) by _running_ the extension, we have this:

![184830205616](https://user-images.githubusercontent.com/734313/49314527-a8686400-f4e2-11e8-95cc-99f2463921e5.png)

That's due the code here https://github.com/meganz/webclient/blob/6c54a7bd2e4e91cf30e824f26cdba493b3911f93/secureboot.js#L2254-L2257

```js
if (is_chrome_firefox && parseInt(Services.appinfo.version) > 27) {
        is_chrome_firefox |= 4;
        jsl.push({f:'js/transfers/meths/firefox-extension.js', n: 'dl_firefox', j: 1, w: 3});
}
```

I.e. that file does requires the [OS.File API](https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/OSFile.jsm) which was only available since Firefox 28, so... PaleMoon having reached version 28 seems the problem here while attempting to use it.

At this point there are a few paths we can follow to workaround the issue, the more straight forward being to continue not loading the file while running under PaleMoon as per for previous versions, but given it does support the OS.File API we may should make it work, although i do find odd having to turn the file into a module for this to work, there is likely another issue at a higher level that's causing the real troubles.

**Comment by Lootyhoof** [comment]
Just providing some input here (for future reference?):

- From a frontend (i.e. adding toolbar buttons etc) perspective, Pale Moon is largely similar to Firefox 24.
- From a backend (i.e. JS capability, APIs etc) perspective, Pale Moon (while fundamentally different from Firefox) could be considered from an API level closest to this (again, only backend, not frontend):
  - 25.x: Firefox 24
  - 26.x: Firefox 24
  - 27.x: Firefox 38
  - 28.x: Firefox 52
- We do not actively aim to block extensions that target Firefox and not Pale Moon. In this case it's because you use `em:strictCompatibility` in `install.rdf`, which won't be true for Pale Moon as you didn't specify it in `install.rdf` until recently.

While this isn't strictly the case per se, it should be enough to help guide what the browser is capable of at particular versions. The [release notes](http://www.palemoon.org/releasenotes.shtml) also state when changes are made (which could include any changes for security purposes - as Pale Moon does receive regular security updates). Please note that Pale Moon does not nor will ever support WebExtensions.

A couple of small nits too (though one more important for users than the other):
- There is no update mechanism currently setup. It's possible to use one of two methods here:
  - If you prefer to self-host, you can add `<em:updateURL>` tags into `install.rdf` and direct that to a relevant `update.xml` file. Users with add-on auto-update enabled will check that file for the latest version information and download updates accordingly. Details of that can still be found on [MDN](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Install_Manifests#updateURL).
  - If you prefer to have this hosted somewhere, it's possible to host it on the [Pale Moon Add-ons Site](https://addons.palemoon.org/extensions/). Details for that can be found [here](https://developer.palemoon.org/Add-ons:Site) and is completely optional. I would be the contact here if this is of interest.
- A much minor nit, but you've listed Pale Moon compatibility as 24 -> 55. 25 was the earliest version to use the current GUID, and 28 is the latest Pale Moon milestone version. 

Hope this helps.
